name: 'Setup'
description: 'Checkouts the project and installs common dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
