name: Distribution Builds

on:
  # Automatically on every tag starting with v
  push:
    tags:
      - v*
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon html:dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html/build/dist
